"""empty message

Revision ID: 09eee8918bdc
Revises: 
Create Date: 2020-05-06 14:45:39.290297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09eee8918bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isSaved',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('isSaved', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('tableStructor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tableName', sa.String(length=64), nullable=True),
    sa.Column('dataSource', sa.Text(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tableName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tableStructor')
    op.drop_table('isSaved')
    # ### end Alembic commands ###
