"""empty message

Revision ID: 21d5af8d3354
Revises: 09eee8918bdc
Create Date: 2020-05-07 11:08:08.525428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21d5af8d3354'
down_revision = '09eee8918bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawlParams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('isSaved',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('isSaved', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('tableStructor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tableName', sa.String(length=64), nullable=True),
    sa.Column('dataSource', sa.Text(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tableName')
    )
    op.drop_index('category', table_name='issaved')
    op.drop_table('issaved')
    op.drop_index('tableName', table_name='tablestructor')
    op.drop_table('tablestructor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablestructor',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tableName', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('dataSource', mysql.TEXT(), nullable=True),
    sa.Column('updateTime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tableName', 'tablestructor', ['tableName'], unique=True)
    op.create_table('issaved',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('isSaved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`isSaved` in (0,1))', name='issaved_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('category', 'issaved', ['category'], unique=True)
    op.drop_table('tableStructor')
    op.drop_table('isSaved')
    op.drop_table('crawlParams')
    # ### end Alembic commands ###
